version: '1.0'
services:
  app:
    build: .
    image: app-statistics-1.0.0
    container_name: app-statistics
    environment:
      DATABASE_URL: jdbc:postgresql://postgres:5432/statistic-db
      DATABASE_PASSWORD: 1234
      DATABASE_USERNAME: root
    ports:
      - "8081:8081"
    volumes:
      - "/var/our_image_storage:/var/our_image_storage"
    depends_on:
      - postgres


  postgres:
    image: postgres:17.3
    container_name: statistic-db
    restart: unless-stopped
    environment:
      POSTGRES_DB: statistic-db
      POSTGRES_USER: root
      POSTGRES_PASSWORD: 1234
    ports:
      - 5445:5432
    volumes:
      - statistic-sensors-db:/var/lib/postgresql/data

volumes:
  statistic-sensors-db:
